version: "3.9"
services:
  singularity:
    image: singularity
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ~/.task:/root/.task
      - ./dummy_taskrc:/root/.taskrc
      - ./.google_credentials:/root/.credentials
      # tmp to make this work locally
      - ~/knox-dev-backend/logseq:/logseq
      - ~/Downloads/kindle:/kindle
    env_file:
      - .env
    working_dir: /app